### ISSUE TITLE
get_reports not working

### ISSUE THREAD

**Issue by Coding-Cactus** [mat-1/repl-talk-api#11]
The `get_reports` thing isn't working 
![image](https://user-images.githubusercontent.com/65423356/93525456-f9528200-f92d-11ea-8107-cbb3fbf9c2f0.png)

**Comment by cursorweb** [comment]
Imagine being unable to log in

**Comment by PotentialStyx** [comment]
Login is broken due to captcha and #12 should fix comments

**Comment by PotentialStyx** [comment]
*getting report comment

**Comment by mat-1** [comment]
Login error is caused due to Captcha (and get_reports requires you to log in), can't fix.
