### ISSUE TITLE
get_reports() ReportList not getting reset before loop

### ISSUE THREAD

**Issue by Coding-Cactus** [mat-1/repl-talk-api#16]
When doing `async for report in await client.get_reports(resolved=False):` multiple times, the `get_reports()` does not reset its list of reports for each loop, this results in an outdated  and duplicated reports list being returned.

This is what I'm talking about:
![image](https://user-images.githubusercontent.com/65423356/99454114-e05e5100-291d-11eb-866f-c021f0b1e438.png)
As you can see, for each loop, the length of the list being returned by `get_reports()` increases by 4 (the number of actual unresolved reports).  Btw the `lst` variable is getting reset correctly each loop.

**Comment by Coding-Cactus** [comment]
Now it just errors if you try to get_reports() more than once (previous thing about it not resetting the list from the previous loop still occurs)
![image](https://user-images.githubusercontent.com/65423356/99574661-95047b00-29cf-11eb-9b7d-144c7b65002d.png)


edit: seems to be working now 🤔
another edit: I actually have no idea what's going on, it sometimes works, but sometimes doesn't

**Comment by PotentialStyx** [comment]
REEEE ILL FIX

**Comment by PotentialStyx** [comment]
Fixed by #17
